### PR TITLE
0033723: Configuration - Removing Genproj and Update files

### PR DESCRIPTION
**Pull request by dpasukhi**
Cleaning repo from not maintaining functionality - genproj and wok

### CODE REVIEW

**Comment by dpasukhi** [comment]
Issue: https://tracker.dev.opencascade.org/view.php?id=33723

**Comment by dpasukhi** [comment]
Dear IKA, fix will need to postponed. The problem cases are our samples. I will update PROD branch later.

**Review by ikochetkova — APPROVED** [review]
No remarks.

**Comment by ikochetkova** [comment]
Please update the mantis link, it is for another issue.

**Comment by dpasukhi** [comment]
http://jenkins-test-10.nnov.opencascade.com/view/CR33723-master-dpasukhi/
Tests are OK

**Review by ikochetkova — APPROVED** [review]
No remarks.

**Pull request merged**
