### PR TITLE
0033671: Coding - GeomTools performance update

### PR DESCRIPTION
**Pull request by dpasukhi**
Update size of buffer for the brep parsing according standard

### CODE REVIEW

**Comment by dpasukhi** [comment]
Issue: https://tracker.dev.opencascade.org/view.php?id=33671

**Review by ikochetkova — DISMISSED** [review]
No remarks.

**Comment by dpasukhi** [comment]
There is a regression on Windows with HLR. Needs to analyze the reason.

**Comment by dpasukhi** [comment]
The solutions looks like as a have positive impact.
Linux testing is more stable to check performance. But I would extend the buffer a little longer (26 or even 32)
<html>
GCC LINUX
<body>
<pre style="color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Total MEMORY difference: 96948369 / 96949356 [-0.00%]

Total CPU difference: 4282.840000000665 / 4581.440000000198 [-6.52%]
--



Total IMAGE difference: 13 / 14246 [0.09%]</pre>
</body>
</html>
Windows MSVC
<html>
<body>
<pre style="color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
Total MEMORY difference: 122586547 / 122855717 [-0.22%]
Total CPU difference: 4103.625 / 3980.109375 [+3.10%]
Total IMAGE difference: 12 / 14311 [0.08%]</pre>
</body>
</html>

<html>

Windows CLANG
<body>
<pre style="color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Total MEMORY difference: 122558458 / 122520503 [+0.03%]
Total CPU difference: 3873.15625 / 3963.34375 [-2.28%]
Total IMAGE difference: 15 / 14292 [0.10%]</pre>
</body>
</html>

**Pull request merged**
