### PR TITLE
0033808: Coding - FreeType Use unsigned point and contour indexing in `FT_Outline`

### PR DESCRIPTION
**Pull request by dpasukhi**
Changes to auto instead of specific type

### CODE REVIEW

**Comment by dpasukhi** [comment]
Build succeed:
https://github.com/dpasukhi/OCCT/actions/runs/10614414703/job/29420278041?pr=4

**Review by ikochetkova — APPROVED** [review]
No remarks.

**Comment by dpasukhi** [comment]
Merged. Marked as closed for internal problem. Merged "as is".

**Comment by dpasukhi** [comment]
Commit: https://github.com/Open-Cascade-SAS/OCCT/commit/7236e83dcc1e7284e66dc61e612154617ef715d6

**Pull request closed without merging**
