### PR TITLE
0033737: Data Exchange, XCAF - Implementing filter tree functionality

### PR DESCRIPTION
**Pull request by dpasukhi**
Implemented base functionality to filter tree with input label to keep.

### CODE REVIEW

**Comment by dpasukhi** [comment]
Issue: https://tracker.dev.opencascade.org/view.php?id=33737

**Review by ikochetkova — APPROVED** [review]
No remarks.

**Comment by dpasukhi** [comment]
New test case is OK on both platform.

**Comment by dpasukhi** [comment]
http://jenkins-test-10.nnov.opencascade.com/view/CR0-test2-master-dpasukhi/view/COMPARE/

**Pull request merged**
