### PR TITLE
0033670: Coding - TopExp_Explorer performance update

### PR DESCRIPTION
**Pull request by dpasukhi**
Reorganized Explorer memory behavior

### CODE REVIEW

**Comment by dpasukhi** [comment]
Issue: https://tracker.dev.opencascade.org/view.php?id=33670

**Review by ikochetkova — DISMISSED** [review]
No remarks

**Comment by dpasukhi** [comment]
There is a regression on Windows with HLR. Needs to analyze the reason.

**Comment by dpasukhi** [comment]
No impact

**Pull request closed without merging**
