### PR TITLE
ModelingAlgorithm - Fix bug of FindRealConstraints()

### PR DESCRIPTION
**Pull request by lavender-lee**
We must use LineTool::Curvature rather than LineTool::Tangency

### CODE REVIEW

**Comment by lavender-lee** [comment]
How to handle CLA? I have no button to click. @dpasukhi

**Comment by dpasukhi** [comment]
At the moment automatic integration of signing CLA into GH in business validation stage and not available.
Please check the link: https://github.com/Open-Cascade-SAS/OCCT/blob/master/.github/CONTRIBUTING.md
Original: https://dev.opencascade.org/get_involved
At the moment only using the development portal is available for CLA signing.

**Review by AtheneNoctuaPt — APPROVED** [review]

**Comment by lavender-lee** [comment]
@dpasukhi I have signed the CLA,  why did you add "CLA watied" again?

**Comment by dpasukhi** [comment]
Please wait the response mail with CLA. Manager will connect with you (today is not working day).
Short details (not all fields are filled, only optional can be slipped), no signature.

**Comment by lavender-lee** [comment]
It's too complicated, I gave up. :(

**Comment by dpasukhi** [comment]
@lavender-lee my apologies. In ongoing month I plan to introduce online CLA singing.
Can I put issue on hold until new CLA process

**Comment by lavender-lee** [comment]
> Can I put issue on hold until new CLA process
@dpasukhi Yes. I will try to contribute code or report bug to OCC. I have been learning the code recently.:)

**Pull request closed without merging**
