### PR TITLE
Add description of BRepAlgoAPI_Algo::Shape()

### PR DESCRIPTION
**Pull request by msmediasofts**
In BRepBuilderAPI_MakeShape, the method Shape() checks if the shape is built and raises an exception if not.

In BRepAlgoAPI_Algo, the method Shape() is overriden. In BRepAlgoAPI_Algo::Shape(), the shape is returned as is (without any check).

The problem is that the description of BRepAlgoAPI_Algo::Shape() is missing. So, the description of the base method, BRepBuilderAPI_MakeShape::Shape(), is used in the documentation.

In the documentation page of [BRepAlgoAPI_Algo](https://dev.opencascade.org/doc/refman/html/class_b_rep_algo_a_p_i___algo.html), the description of Shape() is : "Returns a shape built by the shape construction algorithm. **Raises exception StdFail_NotDone if the shape was not built**", which can lead to unsafe uses.

To fix this, I propose to add a description above BRepAlgoAPI_Algo::Shape() that clearly indicates that the returned shape is not checked.

### CODE REVIEW

**Comment by luzpaz** [comment]
Open a forum thread for the occ devs to see. They don't monitor github repo too closely

**Comment by dpasukhi** [comment]
Dear @msmediasofts,
Thank you for your observation.
We monitor community activity and check the PRs.
Additionally, we will be on our forum where can help you with some questions: https://dev.opencascade.org/forums
I would be very grateful if you could create a ticket in our main bug tracker https://tracker.dev.opencascade.org/
And push into gitolite@git.dev.opencascade.org:occt with branch name "CR<number_of_new_ticket>". Example "CR12345"
If you can't, I'll create a ticket.
If you need more information, let me know.

Best regards Dmitrii.

**Comment by msmediasofts** [comment]
Dear @dpasukhi and @luzpaz,

Thanks for your answers.
I followed the procedure suggested by @dpasukhi. I created a ticket in your issue tracker (ref 0033366), a branch named CR0033366, and the associated PR (#11).

Regards,

Michaël

**Comment by dpasukhi** [comment]
Dear @msmediasofts
You need to create CR33366 branch in gitolite@git.dev.opencascade.org:occt
GitHub repo read only
with full copy of summery as a first line then empty line then description.
I will ask bugmaster to remove CR0033366

**Comment by msmediasofts** [comment]
Commit will be loaded into @dpasukhi 's repo

**Pull request closed without merging**
