### PR TITLE
0033749: Configuration - Update permission draw.sh

### PR DESCRIPTION
**Pull request by ThmsP**
Hello,
Currently, the file draw.sh is installed with very open permissions (777). 
This is probably not a problem for a user installation but we package it with rpm and thus it leaves a root owned file with very insecure permissions.
I have a very limited view of the project thus I may be missing the point of this permissions.

### CODE REVIEW

**Comment by dpasukhi** [comment]
Hello, thank you for the patch. We will analyze it.
Our main bug tracker is https://tracker.dev.opencascade.org/my_view_page.php
PR in OCCT for read only.

**Comment by dpasukhi** [comment]
@ThmsP There an new issue for your ticket https://tracker.dev.opencascade.org/view.php?id=33749
We will proceed with your PR after your signing CLA - https://dev.opencascade.org/get_involved
_
OCCT GitHub repo going to have write access.

**Comment by ThmsP** [comment]
@dpasukhi : Hello, I just signed and send the CLA.

**Review by dpasukhi — APPROVED** [review]

**Comment by dpasukhi** [comment]
Great. I will initiate the test procedure.
After full test cycle the issue will be integrated into IR-1 then it will be integrated into master.

**Comment by dpasukhi** [comment]
Tests are success:
http://jenkins-test-10.nnov.opencascade.com/view/CR33752-master-dpasukhi/view/COMPARE/

**Comment by ThmsP** [comment]
Thanks !

**Comment by dpasukhi** [comment]
@ThmsP the CLA was filled up with some mistakes.
I will keep changes in IR branch for some time waiting for your CLA update.

**Comment by dpasukhi** [comment]
@ThmsP if you mind to share your personal data.
Could I change the author of this comment to OpenCascade? I have no option to allow merge your commit without correct CLA :(

**Comment by ThmsP** [comment]
@dpasukhi Sorry, I just send a correctly filled form.

**Pull request merged**
